# Generated by Django 3.1.3 on 2020-11-25 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detechandwritten',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detect_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detechandwritten',
            name='last_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detect_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
