# Generated by Django 3.1.3 on 2020-11-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0002_auto_20201125_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='detechandwritten',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
