# Generated by Django 3.1.3 on 2020-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0003_detechandwritten_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='detechandwritten',
            name='result',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='detechandwritten',
            name='status',
            field=models.CharField(default='new', max_length=255),
        ),
    ]
